import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import PageLayout from "@/app/components/PageLayout";

const maruburi = localFont({
  src: [
    {
      path: "../fonts/MaruBuri-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-maruburi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${maruburi.variable} antialiased flex flex-col min-h-screen font-korean`}
      >
        <Header />
        <PageLayout>
          {children}
        </PageLayout>
        <Footer />
      </body>
    </html>
  );
}
